#!/bin/sh

set -ue

# must be run as root

# firmware for:
# https://www.amazon.es/dp/B008D8K50Q
# AUGUST DVB-T210
# ID 0572:c68a Conexant Systems (Rockwell), Inc. EyeTV Stick
wget https://github.com/CoreELEC/dvb-firmware/raw/master/firmware/dvb-demod-si2168-d60-01.fw -O /lib/firmware/dvb-demod-si2168-d60-01.fw
wget https://github.com/CoreELEC/dvb-firmware/raw/master/firmware/dvb-tuner-si2141-a10-01.fw -O /lib/firmware/dvb-tuner-si2141-a10-01.fw

curl -1sLf 'https://dl.cloudsmith.io/public/tvheadend/tvheadend/setup.deb.sh' | bash

debconf-set-selections <<EOF
tvheadend	tvheadend/admin_password	password	admin
tvheadend	tvheadend/admin_username	string	admin
EOF

DEBIAN_FRONTEND=noninteractive apt install -y tvheadend git build-essential

# Default TVHeadend scanning and es-Collserola misses many channels for Barcelona.
# I tried https://github.com/stefantalpalaru/w_scan2 , but it wasn't much better.
# Using the "--Generic--: auto-With167kHzOffsets" seems to work better, although it produces many duplicates.
